AWSTemplateFormatVersion: '2010-09-09'
Description: 'mng infra code'

Parameters:
  AZ: 
    Type: 'String'
    Default: 'ap-northeast-1a'
  IngressPublicIp:
    Type: 'String'
    Default: 'x.x.x.x/32'
  MngEC2Role:
    Type: 'String'
    Default: 'kadai1-dev-ec2-role'

Resources:
  #--- Network ------------
  MngVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: 'default'
      CidrBlock: '10.1.0.0/16'
      Tags: 
        - Key: 'Name'
          Value: 'mng-vpc'
  MngSubnet: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 
        Ref: AZ
      VpcId: 
        Ref: MngVPC
      CidrBlock: '10.1.0.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: 'mng-public-subnet'
  MngIGW: 
    Type: AWS::EC2::InternetGateway
    Properties:  
      Tags: 
        - Key: 'Name'
          Value: 'mng-igw'    
  GWAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: 
        Ref: MngVPC 
      InternetGatewayId: 
        Ref: MngIGW 
  MngRT: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId:  
        Ref: MngVPC
      Tags: 
        - Key: 'Name'
          Value: 'mng-rt'  
  mngRoute: 
    Type: AWS::EC2::Route
    DependsOn: GWAttachment
    Properties: 
      RouteTableId:  
        Ref: MngRT
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:  
        Ref: MngIGW
  SubnetRTAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId:  
        Ref: MngSubnet
      RouteTableId:  
        Ref: MngRT

  #----- EC2 Creation --------
  MngInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'mng-ec2-sg'
      GroupDescription: 'access from home'
      VpcId:
        Ref: MngVPC 
      SecurityGroupIngress:
        IpProtocol: 'tcp'
        FromPort: '22'
        ToPort: '22'
        CidrIp: 
          Ref: IngressPublicIp 
  MngInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-06631ebafb3ae5d34'
      InstanceType: 't2.micro'
      KeyName: 'mng-key'
      IamInstanceProfile:
        Ref: MngEC2Role
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: 
            Ref: MngSubnet
          GroupSet:
            - Ref: MngInstanceSG 
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y 
        sudo yum install -y docker
        sudo systemctl start docker
        sudo usermod -a -G docker ec2-user
        sudo systemctl enable docker
        sudo yum install -y jq
      Tags:
        - Key: 'Name'
          Value: 'mng-instance'

Outputs:
  PublicIp:
    Value: !GetAtt [ MngInstance, PublicIp ] 
