AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create Fargate'

Parameters:
  ProjectName:
    Default: 'kadai1'
    Type: String

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-ecr


'
      